### ISSUE TITLE
SDK Does not Works on M1 Macbook Pros

### ISSUE THREAD

**Issue by dvalenzuela** [square/reader-sdk-ios-quickstart#14]
Environment: 

- Apple 13 inch M1 Macbook Pro
- Xcode 12.2

Downloaded the Sample App and the SDK from the website as per [quick start guide](https://developer.squareup.com/docs/reader-sdk/quick-start/step-2) , and just compiled it and I get a linker error.
 
`ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/diegovalenzuela/Downloads/reader-sdk-ios-quickstart-master/SquareReaderSDK.framework/SquareReaderSDK' for architecture arm64`

Cleaned the Project and did a build again and the error persist.

**Comment by StephenJosey** [comment]
Hi @dvalenzuela apologies for delays here. Were you able to resolve this issue? I've tested on a macbook pro and was able to get it running successfully.

**Comment by alexlivenson** [comment]
@StephenJosey I am running into the same issue for the new M1 macbook using SPM

```
ld: warning: Could not find or use auto-linked framework 'SquareInAppPaymentsSDK'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SQIPInAppPaymentsSDK", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any insight would be appreciated

**Comment by alexlivenson** [comment]
@dvalenzuela you might figured this out already, but opening Xcode with Rosetta fixed the issue for me

**Comment by MikeSilvis** [comment]
Reader SDK officially provides M1 support now!
