### ISSUE TITLE
Authorization Error: authorization_invalid_code

### ISSUE THREAD

**Issue by aready87** [square/reader-sdk-ios-quickstart#17]
Sample app as-is builds properly after assigning the Signing & Capability.
Enable Microphone, enable location. Good so far.
Authorize Reader SDK via "Scan QR Code" or "Manually Enter Code", I get an error:
"**Authorization Error** Something went wrong. Please contact the developer of this application and provide them with this error code: authorization_invalid_code"

Tried both the QR code, manually entering the generated code. Also tried code generated via curl.

Xcode version: 13.4.1
Project Format: Xcode 10.0-compatible

Anyone has an idea? Anyone got the app working? I see that the codes haven't be updated in the last 17 months...

**Comment by MikeSilvis** [comment]
@aready87 are you still experiencing this issue? I believe we had an outage around the time u were trying this.
