### ISSUE TITLE
Is there Objective C version ?

### ISSUE THREAD

**Issue by maulikpat** [square/reader-sdk-ios-quickstart#2]
Is there Objective C version ?

**Comment by StephenJosey** [comment]
Unfortunately, there is not an Objective C quick start at this time.

**Comment by maulikpat** [comment]
@StephenJosey I mean for SquareReaderSDK.framework ? Also in this sample framework is missing in project file.

**Comment by StephenJosey** [comment]
Sorry, I misunderstood. The Reader SDK Reference docs shows both Objective C and Swift functions: https://docs.connect.squareup.com/api/reader/ios/

As for the project file, do you mean the `project.pbxproj` file shown here (https://github.com/square/reader-sdk-ios-quickstart/tree/master/ReaderSDKSample.xcodeproj)? For instructions on using this sample, please see: https://docs.connect.squareup.com/payments/readersdk/quickstart

**Comment by maulikpat** [comment]
I downloaded this sample but couldn't compile it. As `SquareReaderSDK.framework` is missing.
<img width="282" alt="screen shot 2018-08-22 at 10 28 49 pm" src="https://user-images.githubusercontent.com/2304770/44478304-e1c74300-a65a-11e8-8107-c6344149edab.png">

Also thanks for : https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDReaderSDK.html

Can you tell me from where I download this `SquareReaderSDK.framework` for Objective C ?

**Comment by StephenJosey** [comment]
Did you install ReaderSDK from Step 2 from the previous link I provided? It tells you how to install the Square ReaderSDK framework. The "Quick Start" guide on our doc site takes you through the steps of getting the sample to work.
https://docs.connect.squareup.com/payments/readersdk/quickstart/page2

The framework works with both Swift and Objective C, there is not a separate download that you need to do. Refer to the link I provided earlier on how to call Objective C functions.

**Comment by maulikpat** [comment]
@StephenJosey  ok so I can only download sdk using terminal with curl right ?

<img width="797" alt="screen shot 2018-08-23 at 12 15 39 pm" src="https://user-images.githubusercontent.com/2304770/44509131-5be4df80-a6ce-11e8-81b9-f89284f6c491.png">

Sorry I was thinking to download from git hub same as POS SDK. 

Thanks for help. I will explore new reader sdk as it now allows to take payments within the app and no need to open POS app from Sqaure.

**Comment by StephenJosey** [comment]
No worries, and that is correct @maulikpat ! Glad you're able to explore our Reader SDK, but please don't hesitate to let us know if you have any other questions or concerns.

**Comment by maulikpat** [comment]
@StephenJosey  One more question Can I test payment from India ? My account is created from USA only. POS SDK is not allowing this due to location service must be enable.

**Comment by maulikpat** [comment]
@StephenJosey  I am ok with real transections. Is it doable ?

**Comment by StephenJosey** [comment]
Sorry for the confusion - no, there is no way to test in India with the POS API or Reader SDK currently.

**Comment by maulikpat** [comment]
:( ok thanks for help.

**Comment by maulikpat** [comment]
@StephenJosey  any chance for Objective C version for demo ?

**Comment by StephenJosey** [comment]
Still no Objective C version, unfortunately. If you need to know about the functions, please check out the Reader SDK Technical Reference: https://docs.connect.squareup.com/api/reader/ios/index.html. It includes both Swift and Objective C.

**Comment by StephenJosey** [comment]
If you plan on more than yourself using this application, you will need to look into OAuth so that they can allow your application to have access to their Square accounts: https://docs.connect.squareup.com/basics/oauth/overview

**Comment by maulikpat** [comment]
No what I mean is, 1 application with 1 square account. Same app with another client's square account configured. So do I need to have separate framework download or same framework can be used for another client with their own credentials.

**Comment by StephenJosey** [comment]
You say "another client's square account", so you mean more than one Square account will be using your application, right? If so, you will need to use OAuth as I mentioned above. It will ask them to sign in to their Square account and give your application access to their account. Each Square account will have their own OAuth access token which you will utilize.

**Comment by maulikpat** [comment]
There will be separate app for each client. There wont be any case like same app with multiple client account setups. So same framework will be used or need to follow this : https://github.com/square/reader-sdk-ios-quickstart/issues/2#issuecomment-415310194
for each client ?

**Comment by StephenJosey** [comment]
I'm sorry, but I don't seem to be following. If you've created one single application and will be installing it on multiple devices, you do not need to re-download the framework. So depending on what you're actually trying to do, please review the following:

1. If you plan on having the same application installed on multiple devices with the same Square account logged in all devices, then there's nothing else you need to do.

2. If you plan on having the same application installed on multiple devices with different Square accounts logged in, then you will need to use OAuth as I mentioned previously.

3. If you're truly creating a new application (you mentioned "separate app") for every device, then yes, you would need to re-download the SDK for every application you create, but I don't believe this is what you actually mean.

**Comment by maulikpat** [comment]
3rd one is what I mean. I have my product and I am giving to my clients with their Square account. These apps will have different bundle IDs as well. So apps will be separate for each client.

**Comment by StephenJosey** [comment]
OK, in that case, you will need to re-download the framework for each one. Just to reiterate, though, if the application is identical in functionality, OAuth would be the easier and more secure route. 

Please let me know if you have additional questions.

**Comment by maulikpat** [comment]
@StephenJosey  thanks for answering all my questions. I will have questions for different areas as I have implemented Reader SDK and testing.
