### ISSUE TITLE
How to get Card details after payment ?

### ISSUE THREAD

**Issue by maulikpat** [square/reader-sdk-ios-quickstart#6]
Hello,

How to get `SQRDCard` after payment in `- (void)checkoutController:(nonnull SQRDCheckoutController *)checkoutController didFinishCheckoutWithResult:(nonnull SQRDCheckoutResult *)result` ?  

Or is there any other way to get card details ?

**Comment by StephenJosey** [comment]
The result is SQRDCheckoutResult: https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDCheckoutResult.html

This object will include a `tenders` (https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDTender.html) field, which has a `cardDetails` (https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDTenderCardDetails.html), which has a `card` (https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDCard.html), which includes the last 4 digits and brand of the card.
