### ISSUE TITLE
Is there any way to detect Magstripe Reader is attached or not ?

### ISSUE THREAD

**Issue by maulikpat** [square/reader-sdk-ios-quickstart#7]
Hi,

Can SDK inform the app/detect that Magstripe Reader is attached via Audio jack or charging point ?

**Comment by maulikpat** [comment]
@StephenJosey any suggestions here ?

**Comment by StephenJosey** [comment]
@maulikpat sorry for the delay! There is currently not a way for the SDK to programmatically detect if the reader is attached. However, via the Reader SDK ReaderSettingsController, you would be able to see if it was successfully connected, and if not, then an error (visible on the UI). See more information here: https://docs.connect.squareup.com/payments/readersdk/overview#reader-settings and https://docs.connect.squareup.com/api/reader/ios/Classes/SQRDReaderSettingsController.html
