### ISSUE TITLE
Can we get Hardware's serial number ?

### ISSUE THREAD

**Issue by maulikpat** [square/reader-sdk-ios-quickstart#9]
Hello,

In our case, we have multiple iOS device and each iOS device will have to connect through Square Reader device separately. So 1:1 pairing this there.

So can we get serial number of reader so we can check which device is connected to which reader ?

**Comment by StephenJosey** [comment]
No, there's currently not a way to see which device is connected to which reader, unfortunately. You will be able to see what device took the payment, of course, in your dashboard (based on the device's name), but there's no way currently to get the serial number of the reader said device is using.
